spring.application.name=Security_project

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db

spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Iziu@4263}

spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / Hibernate

# Production should not modify schema automatically
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Flyway Migration

spring.flyway.enabled=true

spring.flyway.locations=classpath:db/migration


# JWT Configuration

jwt.secret=${JWT_SECRET:secret_key_yena_podrathunu_therila_longkey_123456789}

# 15 minutes
jwt.access-token-expiration=900000

# 30 days
jwt.refresh-token-expiration=2592000000


# Redis

spring.data.redis.host=localhost

spring.data.redis.port=6379

spring.data.redis.password=${REDIS_PASSWORD:}


# Email Configuration

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}

spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true


# File Upload

spring.servlet.multipart.max-file-size=5MB

spring.servlet.multipart.max-request-size=5MB


# Actuator Monitoring

management.endpoints.web.exposure.include=health,info,metrics

management.endpoint.health.show-details=when_authorized


# Logging


logging.level.root=INFO

logging.level.org.springframework.security=INFO


# Server Security

server.error.include-message=never

server.error.include-stacktrace=never